# example netlify.toml
[build]
  command = "yarn workspace site build"
  functions = "functions"
  publish = "site/public"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app. 
  ## Not needed for static site generators.
[[redirects]]
  from = "https://learnwithjason.netlify.com/*"
  to = "https://www.learnwithjason.dev/:splat"
  status = 301
  force = true
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/netlify-dev-plugin#project-detection
  #[dev] 
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
